# Generated by Django 4.0.8 on 2022-10-23 03:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('region', models.CharField(blank=True, max_length=40, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('En espera de aprobacion', 'En espera'), ('denied', 'Denegado'), ('accepted', 'Aceptado')], default='En espera de aprobacion', max_length=100)),
                ('gender', models.PositiveIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')])),
                ('social_status', models.PositiveIntegerField(choices=[(1, 'Plebeyo'), (2, 'Noble')])),
            ],
        ),
    ]
