# Generated by Django 4.0.8 on 2022-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='magical_affinity',
            field=models.PositiveIntegerField(choices=[(1, 'Oscuridad'), (2, 'Luz'), (3, 'Fuego'), (4, 'Agua'), (5, 'Viento'), (6, 'Tierra')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
