# Generated by Django 4.0.8 on 2022-10-24 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grimorios', '0002_profile_magical_affinity_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grimorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.PositiveIntegerField(choices=[(1, 'Sinceridad'), (2, 'Desesperanza'), (3, 'Amor'), (4, 'Buena suerte'), (5, 'Desesperanza')])),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grimorio', to='grimorios.profile')),
            ],
        ),
    ]
